version: '3'
services:
  backendserver:
    build:
      context: .
    ports:
      - '8000:8000'
    command: >
      sh -c "sleep 4 && python manage.py migrate && gunicorn --workers=1 ableton_challenge.wsgi:application --bind 0.0.0.0:8000"
